# Generated by Django 3.2.18 on 2023-04-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_room_user2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_room',
            name='user1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
